name: Node.js CI

on:
  pull_request:

env:
  APP_ENV_NAME: Development

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: print environment variable
        run: echo "My APP_ENV_NAME $APP_ENV_NAME"
      - name: create env file
        run: |
          touch .env
          echo APP_ENV_NAME=Development >> .env
      - name: install dependencies
        working-directory: app
        run: npm ci
      - name: build project
        working-directory: app
        run: npm run build --if-present
      - name: Run tests
        working-directory: app
        run: npm test
