name: Node.js CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APP_ENV_NAME: Development

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        working-directory: app
        run: npm ci
      - name: build project
        working-directory: app
        run: npm run build --if-present
      - name: Run tests
        working-directory: app
        run: npm test
